INSTREAM MACRO STRNG
	MOV AH,0AH				;buffered keyboard input
	LEA DX,STRNG				;load effective address of str into DX
	INT 21H					;service number
ENDM

OUTSTREAM MACRO STRNG
	MOV AH,09H				;string print
	LEA DX,STRNG
	INT 21H
ENDM

LINEFEED MACRO 
	MOV AH,02H				;newline print
	MOV DL,0AH
	INT 21H
ENDM

.MODEL SMALL
.STACK
.DATA
	FPTR DB 0,'CRYSTAL ','TXT',25 DUP('0')
	ERRORCODE DB "UNABLE TO OPEN$"
	BUFF DB 1024 DUP("0")
	HANDL DW 0
.CODE
	MOV AX,@DATA
	MOV DS,AX

	MOV AH,016H
	MOV DX,SEG FPTR
	MOV DS,DX
	MOV DX,OFFSET FPTR
	INT 21H
	OR AL,AL
	JNZ ERROR
	MOV HANDL,DX
	JMP WRITEIT

	ERROR:
	OUTSTREAM ERRORCODE
	
	WRITEIT:
	MOV AH,40H
	MOV DX,SEG BUFF
	MOV DS,DX
	MOV DX,OFFSET BUFF
	MOV BX,WORD PTR HANDL
	MOV CX,1024
	INT 21H

	MOV AH,04CH
	INT 21H
END
